import {volumes} from '../content/volumes.mjs';
import {ExplorerViewModel} from '../viewmodels/explorer.mjs';
const root=document.documentElement;
root.classList.add('js');
const resetInitialScroll=/^#volume-/.test(location.hash)&&performance.getEntriesByType('navigation')[0]?.type!=='back_forward';
if(resetInitialScroll)history.scrollRestoration='manual';
addEventListener('pageshow',()=>{if(resetInitialScroll)requestAnimationFrame(()=>{window.scrollTo({top:0,behavior:'instant'});history.scrollRestoration='auto';});},{once:true});
const vm=new ExplorerViewModel(volumes,location.hash);
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const cards=$$('[data-volume]'),panels=$$('.volume-panel'),dots=$$('[data-dot]');
const viewport=$('.deck-viewport'),deck=$('.book-deck'),dialog=$('#navigation-dialog'),menu=$('.menu-button');
const mobile=matchMedia('(max-width:767px)'),reduced=matchMedia('(prefers-reduced-motion:reduce)'),fine=matchMedia('(pointer:fine)');
const storage={get(){try{return localStorage.getItem('rhyme:motion')}catch{return null}},set(value){try{localStorage.setItem('rhyme:motion',value)}catch{}}};
let active=-1,programmaticUntil=0,scrollTimer,centerTimer,userScrolling=false,skipCenter=false,world=null,worldPromise=null;
function centerCard(index,smooth=true){if(!mobile.matches)return;const card=cards[index];const target=card.offsetLeft-(viewport.clientWidth-card.offsetWidth)/2;programmaticUntil=performance.now()+(smooth?750:200);userScrolling=false;viewport.scrollTo({left:target,behavior:smooth&&!vm.state.motionOff?'smooth':'instant'});clearTimeout(centerTimer);centerTimer=setTimeout(()=>{if(index!==vm.state.activeIndex)return;const current=cards[index];viewport.scrollTo({left:current.offsetLeft-(viewport.clientWidth-current.offsetWidth)/2,behavior:'instant'});programmaticUntil=performance.now()+180;},smooth&&!vm.state.motionOff?600:60);}
function arrange(){if(mobile.matches){cards.forEach(c=>c.style.removeProperty('--book-width'));centerCard(vm.state.activeIndex,false);return;}const w=viewport.clientWidth;const bookWidth=Math.max(115,Math.min(176,w*.19));const activeSpace=bookWidth*.99;const step=(w-activeSpace-12)/11;cards.forEach((card,i)=>{const isActive=i===vm.state.activeIndex;const x=i*step+(i>vm.state.activeIndex?activeSpace-step:0);card.style.setProperty('--book-width',`${bookWidth}px`);card.style.setProperty('--x',`${x}px`);card.style.setProperty('--stack',String(isActive?30:i+1));card.style.setProperty('--angle',isActive?'-10deg':'-64deg');card.style.setProperty('--y',isActive?'-13px':'0px');card.style.setProperty('--z',isActive?'24px':'0px');});}
function select(index,{focus=false,history=true,fromScroll=false}={}){skipCenter=fromScroll;const ok=vm.select(index);skipCenter=false;if(!ok)return;if(history&&location.hash!==vm.hash)window.history.pushState({volume:index},'',vm.hash);if(focus)cards[index].focus({preventScroll:true});}
vm.subscribe(s=>{const changed=active!==s.activeIndex;cards.forEach((card,i)=>{const yes=i===s.activeIndex;card.classList.toggle('is-active',yes);card.setAttribute('aria-selected',String(yes));card.tabIndex=yes?0:-1;panels[i].hidden=!yes;dots[i].setAttribute('aria-pressed',String(yes));});$('[data-previous]').disabled=!s.canPrevious;$('[data-next]').disabled=!s.canNext;$('[data-position]').textContent=`${s.volume.number} OF ${volumes.length}`;$('.deck-track').style.setProperty('--progress',`${s.activeIndex*100}%`);$('.summary-surface').hidden=!s.panelOpen;$('[data-reopen]').hidden=s.panelOpen;$('[data-current-volume-link]').href=new URL(s.volume.route,document.baseURI).pathname;if(changed){panels[s.activeIndex].classList.remove('panel-enter');void panels[s.activeIndex].offsetWidth;panels[s.activeIndex].classList.add('panel-enter');$('[data-announcer]').textContent=`Volume ${s.volume.number} selected. ${s.volume.focus}.`;active=s.activeIndex;if(cards.includes(document.activeElement))cards[active].focus({preventScroll:true});if(!mobile.matches)arrange();if(!skipCenter)centerCard(active,true);}});
let suppressClick=false;
cards.forEach((card,i)=>card.addEventListener('click',()=>{if(suppressClick){suppressClick=false;return;}select(i);}));
dots.forEach((dot,i)=>dot.addEventListener('click',()=>select(i)));
$('[data-previous]').addEventListener('click',()=>select(vm.state.activeIndex-1));
$('[data-next]').addEventListener('click',()=>select(vm.state.activeIndex+1));
viewport.addEventListener('keydown',e=>{let index;switch(e.key){case'ArrowRight':index=Math.min(11,active+1);break;case'ArrowLeft':index=Math.max(0,active-1);break;case'Home':index=0;break;case'End':index=11;break;default:return;}e.preventDefault();select(index,{focus:true});});
$('[data-close-panel]').addEventListener('click',()=>{vm.update({panelOpen:false});$('[data-reopen]').focus({preventScroll:true});});
$('[data-reopen]').addEventListener('click',()=>{vm.update({panelOpen:true});panels[active].focus({preventScroll:true});});
function setMenu(open){vm.update({menuOpen:open});menu.setAttribute('aria-expanded',String(open));if(open){dialog.showModal();document.body.style.overflow='hidden';$('.menu-close').focus();}else{dialog.close();document.body.style.overflow='';menu.focus({preventScroll:true});}}
menu.addEventListener('click',()=>setMenu(true));$('.menu-close').addEventListener('click',()=>setMenu(false));dialog.addEventListener('keydown',e=>{if(e.key!=='Tab')return;const items=[...dialog.querySelectorAll('button,a[href]')];const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});dialog.addEventListener('cancel',e=>{e.preventDefault();setMenu(false);});dialog.addEventListener('click',e=>{if(e.target===dialog)setMenu(false);const link=e.target.closest('a');if(link){setMenu(false);}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!dialog.open&&vm.state.panelOpen){vm.update({panelOpen:false});cards[active].focus({preventScroll:true});}});
addEventListener('popstate',()=>{vm.readHash(location.hash);});addEventListener('hashchange',()=>{vm.readHash(location.hash);});
addEventListener('load',()=>{if(/^#volume-/.test(location.hash)&&performance.getEntriesByType('navigation')[0]?.type!=='back_forward')window.scrollTo({top:0,behavior:'instant'});centerCard(active,false);},{once:true});
// Native touch scrolling retains vertical browser gestures. Mouse drag changes one volume.
let drag=null;
viewport.addEventListener('pointerdown',e=>{if(e.button!==0)return;if(mobile.matches){clearTimeout(centerTimer);programmaticUntil=0;userScrolling=true;}drag={x:e.clientX,y:e.clientY,time:performance.now(),pointer:e.pointerId,moved:false};suppressClick=false;});
viewport.addEventListener('pointermove',e=>{if(!drag||mobile.matches)return;const dx=e.clientX-drag.x,dy=e.clientY-drag.y;if(Math.abs(dx)>12&&Math.abs(dx)>Math.abs(dy)){drag.moved=true;suppressClick=true;viewport.classList.add('dragging');viewport.setPointerCapture(e.pointerId);}});
const finishDrag=e=>{if(!drag)return;const dx=e.clientX-drag.x;const dt=performance.now()-drag.time;if(drag.moved&&(Math.abs(dx)>32||Math.abs(dx)/dt>.3))select(Math.max(0,Math.min(11,active+(dx<0?1:-1))));viewport.classList.remove('dragging');if(viewport.hasPointerCapture(e.pointerId))viewport.releasePointerCapture(e.pointerId);drag=null;setTimeout(()=>suppressClick=false,0);};
viewport.addEventListener('pointerup',finishDrag);viewport.addEventListener('pointercancel',()=>{drag=null;viewport.classList.remove('dragging');suppressClick=false;});
viewport.addEventListener('wheel',()=>{if(mobile.matches){clearTimeout(centerTimer);programmaticUntil=0;userScrolling=true;}},{passive:true});
viewport.addEventListener('scroll',()=>{if(!mobile.matches||!userScrolling)return;clearTimeout(scrollTimer);scrollTimer=setTimeout(()=>{if(performance.now()<programmaticUntil)return;const center=viewport.scrollLeft+viewport.clientWidth/2;const nearest=cards.reduce((best,c,i)=>Math.abs(c.offsetLeft+c.offsetWidth/2-center)<Math.abs(cards[best].offsetLeft+cards[best].offsetWidth/2-center)?i:best,0);userScrolling=false;if(nearest!==active)select(nearest,{fromScroll:true});centerCard(nearest,true);},130);},{passive:true});
let resizeFrame=0;new ResizeObserver(()=>{cancelAnimationFrame(resizeFrame);resizeFrame=requestAnimationFrame(arrange);}).observe(viewport);mobile.addEventListener('change',()=>{requestAnimationFrame(arrange);});
async function ensureWorld(){if(world)return world;if(worldPromise)return worldPromise;worldPromise=import('./world-renderer.mjs').then(m=>m.mountWorld($('#world-canvas'))).then(w=>{world=w;world?.setPaused(vm.state.motionOff);return world;}).catch(()=>{root.dataset.webgl='fallback';return null;});return worldPromise;}
function applyMotion(){const off=reduced.matches||storage.get()==='off';vm.update({motionOff:off});root.dataset.motion=off?'off':'on';const b=$('.motion-control');b.disabled=reduced.matches;b.setAttribute('aria-pressed',String(off));b.setAttribute('aria-label',off?'Enable decorative motion':'Pause decorative motion');$('[data-motion-label]').textContent=reduced.matches?'Reduced motion':off?'Motion off':'Pause motion';b.firstElementChild.textContent=off?'▷':'Ⅱ';world?.setPaused(off);if(!off)ensureWorld();if(off)$$('[data-parallax]').forEach(el=>el.style.translate='0px 0px');}
$('.motion-control').addEventListener('click',()=>{storage.set(vm.state.motionOff?'on':'off');applyMotion();});reduced.addEventListener('change',applyMotion);applyMotion();
let px=0,py=0,pending=false;
function parallax(){pending=false;if(vm.state.motionOff)return;const rect=$('.reading-world').getBoundingClientRect();if(rect.bottom<0)return;const scroll=Math.min(1,Math.max(0,-rect.top/innerHeight));$$('[data-parallax]').forEach(el=>{const depth=Number(el.dataset.parallax);el.style.translate=`${px*depth}px ${py*depth+scroll*depth*.7}px`;});world?.setPointer(px,py);}
$('.reading-world').addEventListener('pointermove',e=>{if(!fine.matches||mobile.matches)return;px=(e.clientX/innerWidth-.5)*1.2;py=(e.clientY/innerHeight-.5)*.8;if(!pending){pending=true;requestAnimationFrame(parallax);}},{passive:true});$('.reading-world').addEventListener('pointerleave',()=>{px=py=0;parallax();});addEventListener('scroll',()=>{if(!pending){pending=true;requestAnimationFrame(parallax);}},{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-revealed');observer.unobserve(e.target);}}),{threshold:.1});$$('.collection-item').forEach(el=>observer.observe(el));
$$('img').forEach(img=>{const fallback=()=>{if(img.dataset.fallback)return;img.dataset.fallback='true';img.removeAttribute('srcset');img.src=new URL('assets/world/fallback.svg',document.baseURI).href;};img.addEventListener('error',fallback);if(img.complete&&!img.naturalWidth)fallback();});
root.dataset.explorer='ready';
