// Original reading focuses; not published book titles or book summaries.
const focuses = [
 ['Notice the small things','Look a little closer.','A word, a sound, a detail you almost missed. Slow down and discover how a small choice can change the way you read a whole passage.',['Attention','Imagery'],'study-guide/reading-practice/notice/','Moonlit arch'],
 ['Find where you belong','Follow the roots.','Explore how places and relationships shape a sense of belonging. Notice who feels at home, who stands apart, and what brings them together.',['Belonging','Setting'],'themes/belonging/','Olive branch'],
 ['See another perspective','A different point of view.','Step beyond your first impression. Ask whose story you are hearing and how the same moment might look through someone else’s eyes.',['Perspective','Narrator'],'themes/perspective/','Mountain peak'],
 ['Build an interpretation','Give your idea a foundation.','Start with a detail from your reading, then build an interpretation around it. Separate what the text tells you from what you infer.',['Evidence','Inference'],'vocabulary/inference/','Classical column'],
 ['Follow an idea','Find the thread.','Connect two moments in your reading. Look for an image, choice, or question that returns, and consider what changes along the way.',['Connection','Theme'],'study-guide/reading-practice/connect/','Golden river'],
 ['Notice what changes','Every step reveals something.','Compare the beginning with a later moment. A small shift in language, a new choice, or a changed relationship can reveal a larger transformation.',['Change','Character'],'themes/change/','Staircase and sun'],
 ['Find your reading direction','Let curiosity lead.','Choose a passage and a question to guide you. Follow a short reading activity at your own pace, with room to pause and return.',['Curiosity','Reflection'],'study-guide/reading-practice/','Compass star'],
 ['Listen to the language','Hear the words differently.','Read a sentence aloud. Listen for its rhythm, its pauses, and its movement. Consider how the pace changes what you feel and notice.',['Rhythm','Sound'],'vocabulary/rhythm/','Paper and branch'],
 ['Follow the echoes','Listen for a returning sound.','Explore the sounds that connect words and lines. Notice how a rhyme creates expectation, adds emphasis, or draws two ideas together.',['Rhyme','Language'],'vocabulary/rhyme/','Ocean wave'],
 ['Step into the setting','A world beyond the page.','Look at the place, time, and conditions surrounding a story. Ask how those surroundings influence a character’s choices and the mood of a scene.',['Setting','Imagery'],'vocabulary/setting/','Stone doorway'],
 ['Make room for another view','See a little further.','One passage can open more than one possibility. Revisit a first impression, listen to another perspective, and return to the text with a new question.',['Perspective','Reflection'],'study-guide/reading-practice/reflect/','Lighthouse'],
 ['Carry the conversation on','The last page is a beginning.','Bring a detail, a connection, or an unanswered question to another reader. Make room for different interpretations and see what you discover together.',['Conversation','Discovery'],'discussion/','Moonlit steps']
];
export const volumes=focuses.map(([focus,headline,summary,themes,activity,art],i)=>({id:i+1,number:String(i+1).padStart(2,'0'),title:`Volume ${String(i+1).padStart(2,'0')}`,focus,headline,summary,themes,activity,art,status:'reading-companion',bookTitle:null,bookSummary:null,accent:['#164f8d','#9d352b','#245d9a','#d2ad50'][i%4],coverImage:`assets/volumes/volume-${String(i+1).padStart(2,'0')}.webp`,thumbnail:`assets/volumes/volume-${String(i+1).padStart(2,'0')}-small.webp`,route:`volumes/${String(i+1).padStart(2,'0')}/`}));
