import {renderClouds} from '../atmosphere/clouds.mjs';
import {esc} from '../../components/html.mjs';
import {volumes} from './catalog.mjs';
import {prepareVolumes} from './view-model.mjs';
const arrow='<span aria-hidden="true">↗</span>';
function cover(v,eager=false){return `<img src="${v.cover}" alt="${esc(v.art)} — concept cover artwork" width="384" height="512" loading="${eager?'eager':'lazy'}">`;}
export function renderExplorer(v){
 const list=prepareVolumes(volumes,v.link);
 const views=[['volumes','Volumes'],['activities','Reading activities'],['resources','Resources'],['about','About']];
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#061726"><title>Rhyme Study Guide — Dylan’s Books</title><meta name="description" content="Twelve reading companions. Choose a volume and discover a new way to read."><link rel="canonical" href="${v.site.origin}${v.link('')}"><link rel="icon" href="${v.link('assets/favicon.svg')}"><link rel="stylesheet" href="${v.link('assets/explorer.css')}"><script type="module" src="${v.link('assets/explorer.js')}"></script></head>
 <body>${[...list.map(b=>`volume-${b.number}`),...views.map(([id])=>id),'all-volumes'].map(id=>`<span class="route-anchor" id="${id}" aria-hidden="true"></span>`).join('')}<a class="skip-link" href="#main">Skip to content</a><div class="reader-shell">
 <div class="world-art" aria-hidden="true"><picture><source media="(max-width:600px)" srcset="${v.link('assets/world/hero-mobile.webp')}"><img src="${v.link('assets/world/hero.webp')}" alt="" width="1536" height="1024"></picture><div class="world-shade"></div><canvas id="world-canvas"></canvas><div class="world-foreground"></div></div>${renderClouds(v.link)}
 <header><a class="wordmark" href="${v.link('')}">RHYME<span>STUDY GUIDE</span></a><nav aria-label="Main navigation">${views.map(([id,label])=>`<a href="#${id}" data-view="${id}" ${id==='volumes'?'aria-current="page"':''}>${label}</a>`).join('')}</nav><button class="motion-control" aria-pressed="false" type="button">Pause motion</button></header>
 <main id="main" tabindex="-1"><section data-scene="volumes" class="volumes-scene" aria-labelledby="hero-title">
 <div class="scene-heading"><div><p class="eyebrow">DYLAN’S BOOKS · THE COLLECTION</p><h1 id="hero-title">Rhyme Study Guide</h1></div><p class="collection-caption">Twelve volumes.<br>A world between the lines.</p></div>
 <div class="selection-stage"><div class="cover-stage" aria-label="Selected book cover">${list.map((b,i)=>`<figure class="selected-cover" data-cover="${i}" ${i?'hidden':''}>${cover(b,!i)}<span class="cover-number">${b.number}</span><figcaption>RHYME · READING COMPANION</figcaption></figure>`).join('')}</div>
 <aside class="reading-panel" aria-label="Selected volume" data-reading-panel tabindex="0"><p class="eyebrow" data-position>Volume 01 of 12</p>${list.map((b,i)=>`<section class="volume-panel" id="volume-panel-${b.number}" aria-labelledby="title-${b.number}" ${i?'hidden':''}><p class="focus-label">ORIGINAL READING FOCUS</p><h2 id="title-${b.number}">${esc(b.headline)}</h2><p class="summary-copy">${esc(b.summary)}</p><ul class="theme-tags">${b.themes.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><details><summary>Read more</summary><p class="expanded-summary">${esc(b.summary)}</p><p>Bring your own book. ${esc(b.focus)}. Choose a passage, gather evidence, and make room for another interpretation.</p><p>These are original reading companions with concept cover artwork. Dylan’s book titles and book-specific summaries will be added when available.</p></details><a class="primary-link" href="${b.href}">Explore this volume <span aria-hidden="true">→</span></a></section>`).join('')}</aside></div>
 <div class="selection-controls"><button data-previous type="button" aria-label="Previous volume">←</button><p class="gesture-hint">SCROLL TO SELECT <span>·</span> TAKE YOUR TIME</p><button data-chooser type="button">All volumes</button><button data-next type="button" aria-label="Next volume">→</button></div>
 <div class="thumbnail-strip" role="group" aria-label="Choose a volume">${list.map((b,i)=>`<button type="button" class="volume-thumb" data-volume="${i}" aria-label="Volume ${b.number}: ${esc(b.focus)}" aria-pressed="${!i}"><img src="${b.smallCover}" alt="" width="180" height="240"><span>${b.number}</span></button>`).join('')}</div><p class="sr-only" role="status" data-announcer>Volume 01 selected.</p></section>
 <section data-scene="activities" class="support-scene" aria-labelledby="activities-title" hidden><p class="eyebrow">BETWEEN THE LINES</p><h2 id="activities-title">Make room for discovery.</h2><p>Bring a book, a little curiosity, and a question. Start wherever you are.</p><div class="resource-grid">${[['Notice','Look closely at a word, a sound, or a detail.','notice/'],['Connect','Follow an idea between two moments.','connect/'],['Reflect','Return to a passage with a new perspective.','reflect/']].map(([title,copy,path])=>`<a href="${v.link('study-guide/reading-practice/'+path)}"><h3>${title}</h3><p>${copy}</p><span>Start reading ${arrow}</span></a>`).join('')}</div></section>
 <section data-scene="resources" class="support-scene" aria-labelledby="resources-title" hidden><p class="eyebrow">KEEP SOMETHING WITH YOU</p><h2 id="resources-title">A little help along the way.</h2><p>Tools for thoughtful reading, on your own or together.</p><div class="resource-grid">${[['Reading notebook','A printable place for details and questions.','resources/reading-sheet/'],['Words & ideas','Explore the language of reading.','vocabulary/'],['Conversation','Find a question worth sharing.','discussion/']].map(([title,copy,path])=>`<a href="${v.link(path)}"><h3>${title}</h3><p>${copy}</p><span>Explore ${arrow}</span></a>`).join('')}</div></section>
 <section data-scene="about" class="support-scene" aria-labelledby="about-title" hidden><p class="eyebrow">DYLAN’S BOOKS</p><h2 id="about-title">A wider mind.<br>A brighter world.</h2><p>Rhyme Study Guide is a place to slow down, look closer, and share what reading reveals.</p><p>The twelve illustrated volumes are original reading companions for use with your own books. Covers are concept artwork; book-specific introductions await Dylan’s approved material.</p><a class="primary-link" href="${v.link('about/')}">About the guide ${arrow}</a></section></main>
 <footer><span>A COMPANION FOR CURIOUS READERS</span><a href="#standard" data-standard>Standard reading layout</a></footer></div>
 <section class="standard-reading" id="standard" aria-labelledby="standard-title"><h2 id="standard-title">Choose a reading companion</h2><p>Original reading focuses, with concept cover artwork.</p><button type="button" data-return>Return to visual reader</button><div class="standard-grid">${list.map(b=>`<a href="${b.href}">${cover(b)}<span>Volume ${b.number}</span><h3>${esc(b.focus)}</h3><p>${esc(b.summary)}</p></a>`).join('')}</div></section>
 <dialog aria-labelledby="chooser-title"><div class="dialog-heading"><h2 id="chooser-title">Choose your volume</h2><button type="button" data-close-chooser aria-label="Close volume chooser">×</button></div><div class="chooser-grid">${list.map((b,i)=>`<button type="button" data-choice="${i}">${cover(b)}<span>Volume ${b.number}</span><span>${esc(b.focus)}</span></button>`).join('')}</div></dialog>
 <noscript><style>.reader-shell{display:none}.standard-reading{display:block}[data-return]{display:none}</style></noscript></body></html>`;
}
export function renderVolumeBody(v){const b=prepareVolumes(volumes,v.link).find(b=>b.id===v.volumeId);return `<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="${v.link('')}">Home</a><span>/</span><a href="${v.link('')}#standard">Volumes</a><span>/ ${b.title}</span></nav><section class="volume-reading"><div class="volume-detail-cover">${cover(b,true)}<span>${b.number}</span></div><div><p class="eyebrow">RHYME STUDY GUIDE · VOLUME ${b.number}</p><h1>${esc(b.headline)}</h1><p class="lead">${esc(b.summary)}</p><p class="eyebrow">ORIGINAL READING FOCUS · ${b.themes.map(esc).join(' & ')}</p><a class="button" href="${b.activityHref}">Begin this reading activity →</a><p class="content-note">This companion offers general reading practice to use with your own book. The illustrated cover is concept artwork; Dylan’s book title and book-specific introduction will be added when available.</p></div></section><section class="quiet-panel"><p class="eyebrow">TAKE A QUESTION WITH YOU</p><h2>What could a second reading reveal?</h2><p>Choose a short passage. Notice one detail, write down the page number, and ask what that detail adds. Keep room for an interpretation different from your own.</p><a class="text-link" href="${v.link('resources/reading-sheet/')}">Open your printable reading notebook ↗</a></section><nav class="chapter-navigation" aria-label="Volume navigation">${b.id>1?`<a class="button button-secondary" href="${v.link(`volumes/${String(b.id-1).padStart(2,'0')}/`)}">← Volume ${String(b.id-1).padStart(2,'0')}</a>`:'<span></span>'}<a class="button button-secondary" href="${v.link('')}#volume-${b.number}">Return to the collection</a>${b.id<12?`<a class="button button-secondary" href="${v.link(`volumes/${String(b.id+1).padStart(2,'0')}/`)}">Volume ${String(b.id+1).padStart(2,'0')} →</a>`:'<span></span>'}</nav>`;}
