import {esc} from '../components/html.mjs';
import {volumes} from '../content/volumes.mjs';
import {prepareVolumes} from '../viewmodels/explorer.mjs';
const arrow='<span aria-hidden="true">↗</span>';
const bookIcon='<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.3"><path d="M12 5C8 2 3 3 2 4v15c4-2 7-1 10 1 3-2 6-3 10-1V4c-3-2-7-1-10 1Zm0 0v15"/></svg>';
function cover(v,eager=false){return `<img src="${v.cover}" srcset="${v.smallCover} 180w, ${v.cover} 384w" sizes="(max-width: 767px) 180px, 220px" alt="${esc(v.art)} — decorative reading companion artwork" width="384" height="512" loading="${eager?'eager':'lazy'}" ${eager?'fetchpriority="high"':''}>`;}
export function renderExplorer(v){
 const list=prepareVolumes(volumes,v.link);
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#061726"><title>Rhyme Study Guide — Dylan’s Books</title><meta name="description" content="Twelve volumes. A world between the lines. Explore Rhyme Study Guide through close reading, curious questions, and conversation."><link rel="canonical" href="${v.site.origin}${v.link('')}"><meta property="og:title" content="Rhyme Study Guide"><meta property="og:description" content="A world between the lines. A reading companion for Dylan’s Books."><meta property="og:image" content="${v.site.origin}${v.link('assets/world/hero.webp')}"><link rel="icon" href="${v.link('assets/favicon.svg')}"><link rel="preload" href="${v.link('assets/fonts/libre-caslon-display-latin-400-normal.woff2')}" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${v.link('assets/explorer.css')}"><script type="module" src="${v.link('assets/explorer.js')}"></script></head>
 <body class="explorer-page">${list.map(b=>`<span id="volume-${b.number}" class="volume-anchor" aria-hidden="true"></span>`).join('')}<a class="skip-link" href="#main">Skip to content</a><div class="reading-world" id="top"><div class="world-art" aria-hidden="true"><div class="world-ink" data-parallax="3"></div><picture class="world-landscape" data-parallax="10"><source media="(max-width:767px)" srcset="${v.link('assets/world/hero-mobile.webp')}"><img src="${v.link('assets/world/hero.webp')}" alt="" width="1536" height="1024" fetchpriority="high"></picture><div class="world-vignette"></div><canvas id="world-canvas"></canvas><div class="world-foreground" data-parallax="22"></div></div>
 <header class="world-header"><button class="menu-button" type="button" aria-label="Open navigation menu" aria-controls="navigation-dialog" aria-expanded="false"><span></span><span></span><span></span></button><a class="wordmark" href="${v.link('')}">RHYME<span>STUDY GUIDE</span></a><a class="header-link" href="${v.link('about/')}">DYLAN’S BOOKS ${arrow}</a><button class="motion-control" type="button" aria-pressed="false" aria-label="Pause decorative motion"><span aria-hidden="true">Ⅱ</span><span data-motion-label>Pause motion</span></button></header>
 <main id="main"><section class="hero-intro" aria-labelledby="hero-title"><p class="eyebrow intro-enter">A COMPANION FOR CURIOUS READERS</p><h1 id="hero-title" class="intro-enter">RHYME<br><span>STUDY GUIDE</span></h1><p class="volume-edition intro-enter">V O L U M E S &nbsp; 1 – 1 2</p><div class="intro-rule intro-enter" aria-hidden="true"><span></span>✦<span></span></div><p class="hero-description intro-enter">Twelve volumes. A world between the lines.<br>Choose a volume. Let your curiosity lead.</p><span class="scene-motto" aria-hidden="true">A WIDER MIND.<br>A BRIGHTER WORLD.</span></section>
 <section class="volume-explorer" aria-label="Explore twelve volumes"><div class="deck-navigation"><span class="deck-label">THE COLLECTION <span aria-hidden="true">/</span> <span data-position>11 OF 12</span></span><div class="deck-buttons"><button type="button" class="circle-button" data-previous aria-label="Previous volume">←</button><button type="button" class="circle-button" data-next aria-label="Next volume">→</button></div></div>
 <div class="explorer-layout"><div class="deck-column"><div class="deck-viewport" tabindex="0" aria-label="Volume carousel. Use left and right arrows, Home or End to select a volume."><div class="book-deck" role="tablist" aria-label="Volumes" aria-orientation="horizontal">${list.map((b,i)=>`<button class="volume-book ${i===10?'is-active':''}" style="--book-accent:${b.accent};--index:${i}" id="tab-${b.number}" type="button" role="tab" aria-label="Volume ${b.number}: ${esc(b.focus)}" aria-selected="${i===10}" aria-controls="volume-panel-${b.number}" tabindex="${i===10?0:-1}" data-volume="${i}"><span class="book-object"><span class="book-back"></span><span class="book-pages"></span><span class="book-face">${cover(b,i===10)}<span class="cover-shade"></span><span class="book-number">${b.number}</span><span class="book-rule" aria-hidden="true"></span><span class="book-imprint">RHYME</span></span><span class="book-spine"></span></span><span class="book-shadow"></span></button>`).join('')}</div></div><div class="deck-track" aria-hidden="true"><span></span></div><div class="volume-dots" role="group" aria-label="Choose volume">${list.map((b,i)=>`<button type="button" data-dot="${i}" aria-label="Select volume ${b.number}" aria-pressed="${i===10}"><span></span></button>`).join('')}</div><p class="deck-hint"><span aria-hidden="true">↔</span> DRAG TO DISCOVER <span class="hint-divider">·</span> SELECT TO EXPLORE</p></div>
 <aside class="summary-wrap" aria-label="Selected volume"><button class="reopen-panel" data-reopen type="button" hidden>Show volume details ↗</button><div class="summary-surface"><button class="close-panel" data-close-panel type="button" aria-label="Hide volume details">×</button>${list.map((b,i)=>`<section id="volume-panel-${b.number}" class="volume-panel" role="tabpanel" aria-labelledby="tab-${b.number}" ${i===10?'':'hidden'} tabindex="0"><div class="summary-top"><span class="summary-number">${b.number}</span><span class="summary-caption">VOLUME<br>READING COMPANION</span></div><p class="focus-label">READING FOCUS</p><h2>${esc(b.headline)}</h2><div class="summary-rule"></div><p class="summary-copy">${esc(b.summary)}</p><ul class="theme-tags" aria-label="Reading themes">${b.themes.map(t=>`<li>${esc(t)}</li>`).join('')}</ul><a class="explore-button" href="${b.href}">${bookIcon}<span>Explore this volume</span><span aria-hidden="true">→</span></a></section>`).join('')}</div></aside></div>
 <p class="sr-only" role="status" aria-live="polite" data-announcer>Volume 11 selected.</p></section><a class="explore-cue" href="#all-volumes"><span>EXPLORE ALL VOLUMES</span><span class="mouse-mark" aria-hidden="true"></span><span aria-hidden="true">⌄</span></a>
 </main></div>
 <section id="all-volumes" class="collection-section" aria-labelledby="collection-title"><div class="section-heading"><div><p class="eyebrow">YOUR NEXT CHAPTER</p><h2 id="collection-title">Every volume.<br>A new way to look.</h2></div><p>Start anywhere. These original reading companions work with any book you have beside you.</p></div><p class="collection-note">Illustrated covers are concept artwork. Book titles and book-specific summaries will be added when available from Dylan.</p><div class="collection-grid">${list.map(b=>`<a class="collection-item" href="${b.href}"><div class="collection-art">${cover(b)}<span>${b.number}</span></div><div><span class="eyebrow">VOLUME ${b.number}</span><h3>${esc(b.focus)}</h3><span class="collection-link">Open companion ${arrow}</span></div></a>`).join('')}</div></section>
 <section class="reading-invitation" aria-labelledby="invitation-title"><span class="invitation-star" aria-hidden="true">✦</span><p class="eyebrow">BETWEEN THE LINES</p><h2 id="invitation-title">The story is only<br>the beginning.</h2><p>A question. A conversation. Something you hadn’t noticed before.</p><a class="outline-link" href="${v.link('study-guide/reading-practice/')}">Find your first reading activity ${arrow}</a></section>
 <footer class="world-footer"><a class="wordmark" href="${v.link('')}">RHYME<span>STUDY GUIDE</span></a><nav aria-label="Footer navigation"><a href="${v.link('about/')}">About the guide</a><a href="${v.link('resources/')}">Reading resources</a><a href="${v.link('about/author/')}">About Dylan</a></nav><p>DYLAN’S BOOKS <span>·</span> MADE WITH CURIOSITY</p></footer>
 <dialog id="navigation-dialog" class="navigation-dialog" aria-labelledby="menu-title"><div class="menu-inner"><div class="menu-top"><p id="menu-title" class="eyebrow">RHYME STUDY GUIDE</p><button type="button" class="circle-button menu-close" aria-label="Close navigation">×</button></div><nav aria-label="Main navigation">${[['01','Home','#top'],['02','All volumes','#all-volumes'],['03','Selected volume',list[10].href],['04','About the guide',v.link('about/project/')],['05','Reading resources',v.link('resources/')]].map(([n,label,href])=>`<a href="${href}" ${n==='03'?'data-current-volume-link':''}><span>${n}</span>${label}<span aria-hidden="true">↗</span></a>`).join('')}</nav><p>A wider mind. A brighter world.</p></div></dialog>
 <noscript><style>.menu-button,.motion-control,.deck-buttons,.close-panel,.volume-dots,.deck-hint{display:none}.collection-section{content-visibility:visible}</style><p class="nojs-note">Choose any companion below to read it. The animated volume selector needs JavaScript.</p></noscript></body></html>`;
}
export function renderVolumeBody(v){const b=prepareVolumes(volumes,v.link).find(b=>b.id===v.volumeId);return `<nav class="breadcrumbs" aria-label="Breadcrumb"><a href="${v.link('')}">Home</a><span>/</span><a href="${v.link('')}#all-volumes">Volumes</a><span>/ ${b.title}</span></nav><section class="volume-reading"><div class="volume-detail-cover">${cover(b,true)}<span>${b.number}</span></div><div><p class="eyebrow">RHYME STUDY GUIDE · VOLUME ${b.number}</p><h1>${esc(b.headline)}</h1><p class="lead">${esc(b.summary)}</p><p class="eyebrow">ORIGINAL READING FOCUS · ${b.themes.map(esc).join(' & ')}</p><a class="button" href="${b.activityHref}">Begin this reading activity →</a><p class="content-note">This companion offers general reading practice to use with your own book. The illustrated cover is concept artwork; Dylan’s book title and book-specific introduction will be added when available.</p></div></section><section class="quiet-panel"><p class="eyebrow">TAKE A QUESTION WITH YOU</p><h2>What could a second reading reveal?</h2><p>Choose a short passage. Notice one detail, write down the page number, and ask what that detail adds. Keep room for an interpretation different from your own.</p><a class="text-link" href="${v.link('resources/reading-sheet/')}">Open your printable reading notebook ↗</a></section><nav class="chapter-navigation" aria-label="Volume navigation">${b.id>1?`<a class="button button-secondary" href="${v.link(`volumes/${String(b.id-1).padStart(2,'0')}/`)}">← Volume ${String(b.id-1).padStart(2,'0')}</a>`:'<span></span>'}<a class="button button-secondary" href="${v.link('')}#volume-${b.number}">Return to the collection</a>${b.id<12?`<a class="button button-secondary" href="${v.link(`volumes/${String(b.id+1).padStart(2,'0')}/`)}">Volume ${String(b.id+1).padStart(2,'0')} →</a>`:'<span></span>'}</nav>`;}
