import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdir,writeFile,readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import path from 'node:path';
const require=createRequire(path.resolve(process.env.QA_MODULE_ROOT??'../browser-runtime','package.json'));
const {chromium}=require('playwright');const {default:AxeBuilder}=require('@axe-core/playwright');
const output=path.resolve('validation/runs/explorer');await mkdir(output,{recursive:true});
const base=process.env.QA_LIVE??'http://127.0.0.1:4173/RhymeStudyGuide/';
const server=process.env.QA_LIVE?null:spawn(process.execPath,['scripts/serve.mjs'],{stdio:['ignore','pipe','pipe']});
if(server)await new Promise((resolve,reject)=>{server.stdout.once('data',resolve);server.once('error',reject);server.once('exit',code=>reject(Error(`Server exit ${code}`)));});
const browser=await chromium.launch({executablePath:process.env.QA_CHROMIUM_PATH,args:['--no-sandbox','--disable-dev-shm-usage','--no-zygote','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],headless:true});
const errors=[],checks=[],a11y=[];const context=await browser.newContext({viewport:{width:1536,height:1024},deviceScaleFactor:1});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.stack));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
const check=(name,value=true)=>{assert.ok(value,name);checks.push(name);};
const selected=async()=>await page.locator('[role=tab][aria-selected=true]').getAttribute('data-volume');
try{
 await page.goto(base,{waitUntil:'networkidle'});await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(1200);check('Homepage title',/RHYME\s+STUDY GUIDE/.test(await page.locator('h1').innerText()));check('Twelve volume tabs',await page.getByRole('tab').count()===12);check('Default volume 11',await selected()==='10');
 await page.screenshot({path:path.join(output,'desktop.png')});await page.screenshot({path:path.join(output,'desktop-full.png'),fullPage:true});
 check('Three.js WebGL initialized',await page.locator('html').getAttribute('data-webgl')==='ready');
 if(process.env.QA_PROBE){await page.setViewportSize({width:390,height:844});await page.waitForTimeout(1000);await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});console.log(JSON.stringify({checks,errors,output}));console.log(await page.locator('.deck-viewport').evaluate(el=>({left:el.scrollLeft,width:el.clientWidth,scrollWidth:el.scrollWidth,active:el.querySelector('.is-active').dataset.volume,deck:getComputedStyle(el.firstElementChild).cssText,offsets:[...el.querySelectorAll('.volume-book')].map(c=>({offset:c.offsetLeft,width:c.offsetWidth}))})));}
 else {
 const audit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();a11y.push({route:'home',violations:audit.violations});
 for(let i=0;i<12;i++){await page.locator(`[data-volume="${i}"] .book-number`).click();assert.equal(await selected(),String(i));assert.equal(await page.locator('.volume-panel:visible .summary-number').textContent(),String(i+1).padStart(2,'0'));assert.ok(page.url().endsWith(`#volume-${String(i+1).padStart(2,'0')}`));}checks.push('All twelve selections update card, summary, and URL');
 check('Last-volume next disabled',await page.locator('[data-next]').isDisabled());await page.locator('[data-previous]').click();check('Previous control works',await selected()==='10');
 await page.locator('[role=tab][aria-selected=true]').focus();await page.keyboard.press('Home');check('Home key and first-volume boundary',await selected()==='0'&&await page.locator('[data-previous]').isDisabled());await page.keyboard.press('ArrowRight');check('Right arrow keyboard selection',await selected()==='1');await page.keyboard.press('End');check('End key selects last',await selected()==='11');
 await page.locator('[data-dot="2"]').click();await page.locator('[data-dot="6"]').click();await page.goBack();check('Back restores selected volume',await selected()==='2');await page.goForward();check('Forward restores selected volume',await selected()==='6');await page.reload({waitUntil:'networkidle'});check('Refresh retains deep-link selection',await selected()==='6');check('Deep-link refresh stays at hero',await page.evaluate(()=>scrollY)===0);
 await page.locator('[data-close-panel]').click();check('Details hide',await page.locator('.summary-surface').isHidden());await page.locator('[data-reopen]').click();check('Details reopen',await page.locator('.summary-surface').isVisible());
 await page.locator('.menu-button').click();check('Menu opens and focus enters',await page.locator('dialog').isVisible()&&await page.locator('.menu-close').evaluate(el=>el===document.activeElement));await page.keyboard.press('Shift+Tab');check('Menu traps keyboard focus',await page.evaluate(()=>document.querySelector('dialog').contains(document.activeElement)));await page.keyboard.press('Escape');check('Menu escape restores focus',await page.locator('dialog').isHidden()&&await page.locator('.menu-button').evaluate(el=>el===document.activeElement));
 await page.locator('[data-dot="5"]').click();const box=await page.locator('.deck-viewport').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+100);await page.mouse.down();await page.mouse.move(box.x+box.width/2-160,box.y+105,{steps:10});await page.mouse.up();check('Desktop drag selects next volume',await selected()==='6');
 await page.locator('.motion-control').click();check('Motion toggle stops motion',await page.locator('html').getAttribute('data-motion')==='off');await page.reload({waitUntil:'networkidle'});check('Motion choice persists',await page.locator('html').getAttribute('data-motion')==='off');await page.locator('.motion-control').click();
 await page.emulateMedia({reducedMotion:'reduce'});await page.waitForFunction(()=>document.documentElement.dataset.motion==='off');check('Reduced motion updates live',await page.locator('html').getAttribute('data-motion')==='off');check('Reduced motion remains respected',await page.locator('.motion-control').isDisabled());await page.emulateMedia({reducedMotion:'no-preference'});
 for(const width of [320,390,768,1024,1440,1920]){await page.setViewportSize({width,height:900});await page.waitForTimeout(180);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,`Overflow at ${width}`);}checks.push('No overflow at six target viewport widths');
 await page.setViewportSize({width:390,height:844});await page.goto(base+'#volume-11',{waitUntil:'networkidle'});await page.waitForTimeout(1000);await page.screenshot({path:path.join(output,'mobile.png'),fullPage:true});
 // Native scroll/snap pathway used by touch swiping.
 await page.locator('.deck-viewport').dispatchEvent('wheel',{deltaX:-194});await page.locator('.deck-viewport').evaluate(el=>el.scrollTo({left:el.scrollLeft-194,behavior:'instant'}));await page.waitForTimeout(600);check('Mobile carousel scroll selects adjacent volume',await selected()==='9');await page.locator('[data-next]').click();await page.waitForTimeout(850);check('Mobile arrow recenters active card',await page.locator('.deck-viewport').evaluate(el=>{const c=el.querySelector('.is-active');return Math.abs(c.offsetLeft+c.offsetWidth/2-(el.scrollLeft+el.clientWidth/2))<5;}));
 const mobileAudit=await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze();a11y.push({route:'mobile-home',violations:mobileAudit.violations});
 await page.locator('.volume-panel:visible .explore-button').click();check('Volume CTA leads to real companion',page.url().includes('/volumes/11/'));await page.getByRole('link',{name:'Begin this reading activity'}).click();check('Companion links to real learning activity',page.url().includes('/reflect/'));
 const manifest=JSON.parse(await readFile('build-manifest.json','utf8'));
 for(const file of manifest.files){const response=await page.goto(base+(file==='index.html'?'':file.replace(/index.html$/,'')),{waitUntil:'load'});assert.equal(response.status(),200,file);assert.equal(await page.locator('h1').count(),1,file);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,file);}
 checks.push('All 40 pages render without mobile overflow');
 await page.goto(base+'volumes/11/',{waitUntil:'networkidle'});a11y.push({route:'volume',violations:(await new AxeBuilder({page}).withTags(['wcag2a','wcag2aa','wcag21aa']).analyze()).violations});await page.screenshot({path:path.join(output,'volume-mobile.png'),fullPage:true});
 await page.goto(base+'discussion/',{waitUntil:'networkidle'});let old=await page.locator('.prompt-panel:visible h2').textContent();await page.locator('[data-next-prompt]').click();check('Existing discussion interaction retained',old!==await page.locator('.prompt-panel:visible h2').textContent());
 await page.goto(base+'study-guide/reading-practice/notice/');await page.getByLabel('What stayed with you?').fill('A second reading reveals another detail.');await page.waitForTimeout(450);await page.reload();check('Reading notes persist',await page.getByLabel('What stayed with you?').inputValue()==='A second reading reveals another detail.');
 const nojs=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});const p=await nojs.newPage();await p.goto(base);await p.locator('.collection-item').first().click();check('No-JavaScript volume navigation works',p.url().includes('/volumes/01/'));await p.getByRole('link',{name:'Begin this reading activity'}).click();check('No-JavaScript activity navigation works',p.url().includes('/notice/'));await nojs.close();
 await page.goto(base+'#volume-99',{waitUntil:'networkidle'});check('Invalid volume hash falls back to volume 11',await selected()==='10');
 const fallbackContext=await browser.newContext();await fallbackContext.route('**/assets/volumes/*.webp',r=>r.abort());const fp=await fallbackContext.newPage();await fp.goto(base,{waitUntil:'networkidle'});check('Broken cover uses fallback',await fp.locator('.volume-book img').first().getAttribute('data-fallback')==='true');check('Fallback cover loads',await fp.locator('.volume-book img').first().evaluate(i=>i.naturalWidth>0));await fallbackContext.close();
 const touchContext=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const touchPage=await touchContext.newPage();await touchPage.goto(base+'#volume-11',{waitUntil:'networkidle'});await touchPage.waitForTimeout(800);const cdp=await touchContext.newCDPSession(touchPage);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:100,y:540}]});for(let x=120;x<=280;x+=20){await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:540}]});await touchPage.waitForTimeout(35);}await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await touchPage.waitForTimeout(1100);const touched=await touchPage.locator('[role=tab][aria-selected=true]').getAttribute('data-volume');check('Real touch swipe updates selection',Number(touched)<10);check('Touch summary stays synchronized',await touchPage.locator('.volume-panel:visible .summary-number').textContent()===String(Number(touched)+1).padStart(2,'0'));await touchContext.close();
 const noGpu=await browser.newContext();await noGpu.addInitScript(()=>{const get=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type.startsWith('webgl')?null:get.call(this,type,...args);};});const gp=await noGpu.newPage();await gp.goto(base,{waitUntil:'networkidle'});await gp.locator('[data-dot="3"]').click();check('WebGL failure preserves volume selection',await gp.locator('.volume-panel:visible .summary-number').textContent()==='04');check('WebGL fallback reported',await gp.locator('html').getAttribute('data-webgl')==='fallback');await noGpu.close();
 check('No uncaught browser errors',errors.length===0);check('No automated accessibility violations',a11y.every(a=>a.violations.length===0));
 }
}catch(e){errors.push(e.stack);await page.screenshot({path:path.join(output,'failure.png'),fullPage:true}).catch(()=>{});console.error(e.stack);}
finally{await writeFile(path.join(output,'results.json'),JSON.stringify({passed:errors.length===0,checks,errors,a11y},null,2));await browser.close();server?.kill();}
console.log(JSON.stringify({passed:errors.length===0,checks,errors,output},null,2));if(errors.length)process.exitCode=1;
